config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1 , parameter: {name: 'id' , value: 1},constraints: ApiConstraints.new(version: 1, default: true) do
      resources :podcasts  
      resources :users do
        get :following, :followers
      end
    end
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users do
    member do
     get :podcasts
   end
 end
 resources :podcasts do
  member do
    post :follow
    post :unfollow
  end
end
resources :podcasts, 	  		only: [:index, :show,   :new, :create, :destroy]
resources :sessions,   		    only: [:new, :create, :destroy]
resources :relationships,       only: [:create, :destroy]
root to: 'static_pages#home'
match '/about',  to: 'static_pages#about', via: 'get'
match '/contact',  to: 'static_pages#contact', via: 'get'
match '/community',  to: 'users#community',   via: 'get'
match '/signup',  to: 'users#new',            via: 'get'
match '/signin',  to: 'sessions#new',         via: 'get'
match '/signout', to: 'sessions#destroy',     via: 'delete'
  #get '/signin',  to: 'device/sessions#new'
  #delete '/signout', to: 'device/sessions#destroy'
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
   <div class="alert alert-danger">
      <p>The form contains <%= pluralize(object.errors.count, "error") %>:</p>
    
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
    </div>
  </div>
<% end %>

app/views/shared/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/shared/_profile.html.erb
<section>
  <article id="user">
    <% if(@user.image.file.nil?)%>
    <%= gravatar_pic @user, size: 150 %>
    <% else %>
    <img src="data:image/jpeg;base64,<%= @user.image64 %>" />
    <% end %>
    <p><%= @user.name %> </p>
  </article>
  <article id="follow">
    <%= render 'shared/stats' %>
  </article>
  <% if(@user.podcasts.length > 0) %>
  <article id="podcasts">
    <p> Podcasts </p>
    <div class="followed-podcasts">
      <% @user.podcasts.limit(3).each do |p| %>
      <img src="data:image/jpeg;base64,<%= p.image64 %>" />
      <% end %>

      <%= link_to "view more", podcasts_user_path(@user), {class: "all-podcasts"}  %>

    </div>
  </article>
  <% end %>
</section>

app/views/shared/_profile_home.html.erb
<section>
  <article id="user">
    <% if(current_user.image.file.nil?)%>
    <%= gravatar_pic current_user, size: 150 %>
    <% else %>
      <img src="data:image/jpeg;base64,<%= current_user.image64 %>" />
    <% end %>
    <p><%= current_user.name %> </p>
  </article>
  <article id="follow">
    <%= render 'shared/stats' %>
  </article>
  <article id="podcasts">
    <p> Podcasts </p>
    <div class="followed-podcasts">
      <% current_user.podcasts.limit(3).each do |p| %>
      <img src="data:image/jpeg;base64,<%= p.image64 %>" />
      <% end %>
      <%= link_to "view more", podcasts_user_path(current_user), {class: "all-podcasts"}  %>

    </div>
  </article>
</section>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <div class="following">
    <a href="<%= following_user_path(@user) %>">
      Following
      <strong id="following" class="stat">
        <%= @user.following.count %>
      </strong>
    </a>
  </div>
  <div class="followers">
    <a href="<%= followers_user_path(@user) %>">
      Followers
      <strong id="followers" class="stat">
        <%= @user.followers.count %>
      </strong>
    </a>
  </div>
</div>