config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1 , parameter: {name: 'id' , value: 1},constraints: ApiConstraints.new(version: 1, default: true) do
      resources :podcasts  
      resources :users do
        get :following, :followers
      end
    end
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users do
    member do
     get :podcasts
   end
 end
 resources :podcasts do
  member do
    post :follow
    post :unfollow
  end
end
resources :podcasts, 	  		only: [:index, :show,   :new, :create, :destroy]
resources :sessions,   		    only: [:new, :create, :destroy]
resources :relationships,       only: [:create, :destroy]
root to: 'static_pages#home'
match '/about',  to: 'static_pages#about', via: 'get'
match '/contact',  to: 'static_pages#contact', via: 'get'
match '/community',  to: 'users#community',   via: 'get'
match '/signup',  to: 'users#new',            via: 'get'
match '/signin',  to: 'sessions#new',         via: 'get'
match '/signout', to: 'sessions#destroy',     via: 'delete'
  #get '/signin',  to: 'device/sessions#new'
  #delete '/signout', to: 'device/sessions#destroy'
end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  has_and_belongs_to_many :users
  validates :name, presence: true, length: { maximum: 50 }
  validates :category, presence: true, length: { maximum: 50 }
  validates :description, presence: true
  validates :url, presence: true
  mount_uploader :image, ImageUploader

end

app/controllers/api/v1/podcasts_controller.rb
module Api
	module V1
		class PodcastsController < ApplicationController
			respond_to :json

			def index
				begin
					respond_with Podcast.all
				rescue
					respond_with "A ninja captured my podcast list"
				end
			end

			def show
				begin
					respond_with Podcast.find(params[:id])
				rescue
					respond_with "A ninja captured this podcast"
				end
			end
		end
	end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :signed_in_user,
  only: [:show]
  def index
    @podcasts = Podcast.paginate(page: params[:page]).per_page(5)
  end
  def new
    @podcast = new Podcast
  end 
  def show
    @podcast = Podcast.find(params[:id])
  end
  def create
    @podcast = Podcast.(podcast_params)
      @podcast.save
  end
  def follow
    @podcast = Podcast.find(params[:id])
    current_user.podcasts << @podcast
    redirect_to @podcast
  end
  def unfollow
    @podcast = Podcast.find(params[:id])
    current_user.podcasts.destroy(@podcast)
    redirect_to @podcast
  end
  private
  def podcast_params
    params.require(:podcast).permit(:name,:category,:description,:url, :image, :remote_image_url)
  end
end

app/views/podcasts/_podcast.html.erb
<li>
  <img src="data:image/jpeg;base64,<%= podcast.image64 %>"/>
  <h2><%=  link_to podcast.name, podcast %></h2>
  <p><%=  podcast.description %></p>
  <p><%= link_to podcast.name + "'s website", "http://#{podcast.url}" %></p>
  <hr/>
</li>

app/views/podcasts/index.html.erb
<% provide(:title, 'Podcasts') %>
<section class="podcasts">
<h1>Podcasts</h1>
<ul class="podcasts">
  <%= render @podcasts %>
</ul>
<%= will_paginate @users, previous_label: ('PREVIOUS'), next_label: ('NEXT') %>
</section>

app/views/podcasts/show.html.erb
<% provide(:title, @podcast.name) %>

<section class="show-podcast">
	<img src="data:image/jpeg;base64,<%= @podcast.image64 %>" />
	<span><%= @podcast.name %></span>

	<p> <%= @podcast.description %> </p>
	<br/>
	<% if !current_user.podcasts.exists?(@podcast.id) %>
	<%= button_to 'Follow Podcast', follow_podcast_path(@podcast.id), class: "follow" %>
	<% else %>
	<%= button_to 'Unfollow Podcast', unfollow_podcast_path(@podcast.id), class: "follow" %>
	<% end %>
</section>