config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1 , parameter: {name: 'id' , value: 1},constraints: ApiConstraints.new(version: 1, default: true) do
      resources :podcasts  
      resources :users do
        get :following, :followers
      end
    end
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users do
    member do
     get :podcasts
   end
 end
 resources :podcasts do
  member do
    post :follow
    post :unfollow
  end
end
resources :podcasts, 	  		only: [:index, :show,   :new, :create, :destroy]
resources :sessions,   		    only: [:new, :create, :destroy]
resources :relationships,       only: [:create, :destroy]
root to: 'static_pages#home'
match '/about',  to: 'static_pages#about', via: 'get'
match '/contact',  to: 'static_pages#contact', via: 'get'
match '/community',  to: 'users#community',   via: 'get'
match '/signup',  to: 'users#new',            via: 'get'
match '/signin',  to: 'sessions#new',         via: 'get'
match '/signout', to: 'sessions#destroy',     via: 'delete'
  #get '/signin',  to: 'device/sessions#new'
  #delete '/signout', to: 'device/sessions#destroy'
end

app/views/layouts/_footer.html.erb
<footer>
  <div id="footer-content">
  <small>
    Podcast Central
    by <a href="https://github.com/drodrigo/">Dyego Rodrigo</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header id="main_header">
	<nav class="top-bar" data-topbar="">

		<section id="header-section">
			<ul class="logo">
				<li class="name">
					<h1><a href="/">PODCAST CENTRAL</a></h1>
				</li>
			</ul>
			<ul class="menu-right">
				<li class="main-menu"><%= link_to "PODCASTS", podcasts_path %></li>
				<li class="main-menu"><%= link_to "COMMUNITY", users_path %></li>
				<li class="main-menu">
				<% if signed_in? %>
				 	<% if current_user.image.file.nil? %>
						<a id="dropdown-menu"  href="#"><%= gravatar_pic current_user %> <b class="caret"> </b></a>
					<% else %>
						<a id="dropdown-menu"  href="#"><img src="data:image/jpeg;base64,<%= current_user.image64 %>" /> <b class="caret"> </b></a>
					<% end %>
						<ul class="submenu">
							<li class="submenu"><%= link_to "PROFILE", current_user %>
							</li>
							<li class="submenu"><%= link_to "SETTINGS", edit_user_path(current_user) %></li>
							<li class="submenu">
								<%= link_to "SIGN OUT", signout_path, method: "delete" %>
							</li>
						</ul>
					</li>
				<% else %>
				<li><%= link_to "SIGN IN", signin_path %></li>
				<% end %>
			</ul>
			<ul class="menu-icon">
				<%= image_tag("icons/sprite.png", class: "intro-img") %>
			</ul>
		</section>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><%= full_title(yield(:title)) %></title>
	<%= favicon_link_tag  'favicon.ico'%>
 	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div id="wrapper">
		<section id="header-section">
			<%= render 'layouts/header' %>
		</section>
		<section id="content-section">
			<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
		</section>
		<%= debug(params) if Rails.env.development? %>
		<section id="footer-section">
			<%= render 'layouts/footer' %>
		</section>

	</div>
</body>
</html>